### ISSUE TITLE
Cannot build hmatrix on OSX

### ISSUE THREAD

**Issue by yongqli** [albertoruiz/hmatrix#100]
https://gist.github.com/yongqli/867cbc94cb85baa1cddf

**Comment by mkraemer67** [comment]
This fix also works on cygwin by the way. But I had to define __APPLE__ by hand. :)

**Comment by GongYiLiao** [comment]
MinGHC with Mingw-w64 4.9.2 has the similar problem, the "random_data" C struct is not defined in stdlib.h as well.

**Comment by idontgetoutmuch** [comment]
@albertoruiz I suggest we close this issue as I imagine the world has changed quite a lot. I have done quite a bit of work in the last few weeks on getting hmatrix to build on OSX. It builds for me installing the required packages via homebrew and also via nix.

**Comment by albertoruiz** [comment]
Ok, thanks!
