### ISSUE TITLE
3 Test Failures normv2CF, normv2F, normmFroCF

### ISSUE THREAD

**Issue by noahdiewald** [albertoruiz/hmatrix#102]
This is on Arch Linux with:

* ghc 7.8.3-2
* blas 3.5.0-1
* gsl 1.16-1

<pre>
> Numeric.LinearAlgebra.Tests.runTests 20
...
------ some unit tests
### Failure in: 16:1                        
normv2CF
### Failure in: 16:3                        
normv2F
### Failure in: 17:13                       
normmFroCF
Cases: 62  Tried: 62  Errors: 0  Failures: 3
*** Exception: ExitFailure 1
</pre>

**Comment by unhammer** [comment]
I also get

    5.477225575051661
    5.477225575051661 :+ 0.0
    5.477226 :+ 0.0

but runTests 20 gives

    ### Failure in: 16:1                        
    normv2CF
    ### Failure in: 17:13                       
    normmFroCF
    Cases: 62  Tried: 62  Errors: 0  Failures: 2
    *** Exception: ExitFailure 1

**Comment by albertoruiz** [comment]
This test was not very useful and has been removed in the most recent version. I think it is just an issue of rounding in single precision operations, which gives different results in different systems.
