### ISSUE TITLE
storable-complex not needed for base-4.8

### ISSUE THREAD

**Issue by pacak** [albertoruiz/hmatrix#103]
Storable instances for Complex are provided by the new and storable-complex fails to compile because of duplicated instances.

**Comment by albertoruiz** [comment]
Thanks for the bug report, I will fix the dependencies soon.

**Comment by albertoruiz** [comment]
Fixed in the new branch "710" (but hmatrix-tests is not yet updated).

**Comment by cartazio** [comment]
ummm, storable complex now should work fine on 7.10, the instances are empty there, i did the fix to make sure! if not, please report a bug to me!
