### ISSUE TITLE
Cannot build on GHC 7.10

### ISSUE THREAD

**Issue by yongqli** [albertoruiz/hmatrix#108]
src/Numeric/Chain.hs:64:10:
        Non type-variable argument in the constraint: A.IArray a (Maybe a)
        (Use FlexibleContexts to permit this)
        When checking that ‘subArray’ has the inferred type
          subArray :: forall i (a :: * -> * -> *) a1.
                      (Num i, A.Ix i, A.IArray a (Maybe a1)) =>
                      i -> a i (Maybe a1)
        In an equation for ‘newWorkSpaceCost’:
            newWorkSpaceCost n
              = A.array (1, n) $ map (\ i -> (i, subArray i)) [1 .. n]
              where
                  subArray i = A.listArray (1, i) (repeat Nothing)

    src/Numeric/Chain.hs:68:10:
        Non type-variable argument in the constraint: A.IArray a (Maybe a)
        (Use FlexibleContexts to permit this)
        When checking that ‘subArray’ has the inferred type
          subArray :: forall i (a :: * -> * -> *) a1.
                      (Num i, A.Ix i, A.IArray a (Maybe a1)) =>
                      i -> a i (Maybe a1)
        In an equation for ‘newWorkSpaceIndexes’:
            newWorkSpaceIndexes n
              = A.array (1, n) $ map (\ i -> (i, subArray i)) [1 .. n]
              where
                  subArray i = A.listArray (1, i) (repeat Nothing)
    cabal: Error: some packages failed to install:
    hmatrix-0.16.1.3 failed during the building phase. The exception was:

**Comment by albertoruiz** [comment]
I think this is already fixed by commit https://github.com/albertoruiz/hmatrix/commit/815ef730c17bcdf5c6dcbd27c32da9ef944ae498 (not yet in hackage).

**Comment by taruti** [comment]
Any progress on getting this to Hackage?

**Comment by albertoruiz** [comment]
I think this is in Hackage since 0.16.1.4:

https://hackage.haskell.org/package/hmatrix-0.16.1.5/src/src/Numeric/Chain.hs
