### ISSUE TITLE
Sparse.hs not exported

### ISSUE THREAD

**Issue by ocramz** [albertoruiz/hmatrix#111]
as per title. Is this a bug or a feature?

**Comment by albertoruiz** [comment]
It is a "feature". The entities of this module are reexported by the main modules: 

https://hackage.haskell.org/package/hmatrix-0.16.1.4/docs/Numeric-LinearAlgebra-Data.html

https://hackage.haskell.org/package/hmatrix-0.16.1.4/docs/Numeric-LinearAlgebra-HMatrix.html#v:-33--35--62-
