### ISSUE TITLE
Static Cholesky?

### ISSUE THREAD

**Issue by idontgetoutmuch** [albertoruiz/hmatrix#116]
I couldn't find a static version of Cholesky. I'd be happy to provide one but I don't want to duplicate anything that might be in progress.

**Comment by albertoruiz** [comment]
That function would be welcome!
(I think that the "maybe" variant would be nice for the static interface).

**Comment by idontgetoutmuch** [comment]
Bother! I didn't do the "maybe" variant - sorry. I am going to close this anyway. If someone (maybe me) wants the "maybe" version we can add it later.
