### ISSUE TITLE
Could not find module ‘Data.Packed.Convert’

### ISSUE THREAD

**Issue by kindlychung** [albertoruiz/hmatrix#120]
When loading the inplace.hs file from the examples, ghci complains that 

    Could not find module ‘Data.Packed.Convert’

Maybe the examples need to be updated.

Thanks!

**Comment by albertoruiz** [comment]
Yes, the examples must be updated to the new interface.
I have made a few changes and commented out some functions in inplace.hs so it compiles, but the whole set of examples must be updated.
Thanks for the bug report!
