### ISSUE TITLE
Make a new version / release?

### ISSUE THREAD

**Issue by k-bx** [albertoruiz/hmatrix#121]
Hi! When building latest hmatrix with ghc HEAD I'm getting the following error:

```
src/Data/Packed/Internal/Numeric.hs:709:5: error:
    Could not deduce (Linear t0 v)
    from the context: Linear t v
      bound by the type signature for: addL :: Linear t v => v -> v -> v
      at src/Data/Packed/Internal/Numeric.hs:709:5-26
    The type variable ‘t0’ is ambiguous
    In the ambiguity check for the type signature for ‘addL’:
      addL :: forall t v. Linear t v => v -> v -> v
    To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
    When checking the class method:
      addL :: forall t v. Linear t v => v -> v -> v
    In the class declaration for ‘Linear’
cabal: Error: some packages failed to install:
hmatrix-0.16.1.5 failed during the building phase. The exception was:
```

But after looking at sources, I don't see this type-signature anymore, it's as simple as `addL :: v -> v -> v`

Can it be that we need one more release that ships that code to hackage? Thanks!

**Comment by albertoruiz** [comment]
I have not tested HEAD yet, perhaps we must enable "AllowAmbiguousTypes" .
The goal of the the next release is clean compilation on 7.10 and removing the old interface, when this is ready I will try the next ghc version...
Thanks!

**Comment by k-bx** [comment]
@albertoruiz I was actually getting this error on ghc 7.10, not on head (I noticed this later), so I'll wait for 7.10 release and check it out again. Thanks!

**Comment by albertoruiz** [comment]
This is strange, in my machine, hmatrix-0.16.1.5 compiles ok (with warnings) on ghc-7.10.1.
(The version in the develop branch should compile cleanly, including hmatrix-tests.)
Can you confirm that you get this error on 7.10.1?

**Comment by k-bx** [comment]
@albertoruiz ok, sorry once again. So it does build on ghc-7.10.1, and it does fail with an error that I've posted on current HEAD.

**Comment by albertoruiz** [comment]
no problem, thanks!
