### ISSUE TITLE
`-msse` obviously breaks other architectures

### ISSUE THREAD

**Issue by nomeata** [albertoruiz/hmatrix#123]
Hi,

it is currently not possible to build `hmatrix` on non-intel architectures, due to the `-msse` flag passed in `cc-options`. Please guard that by a cabal conditional that checks the architecture.

Thanks,
Joachim

**Comment by albertoruiz** [comment]
Hi Joachim, I have added the check in the develop branch.
Thanks for your bug report!
Alberto
