### ISSUE TITLE
LDL decomposition

### ISSUE THREAD

**Issue by amigalemming** [albertoruiz/hmatrix#129]
I would like to have the LDL decomposition in hmatrix additionally to the Cholesky decomposition.

**Comment by albertoruiz** [comment]
I plan to add an interface to dsytrf / dsytrs.
Thanks for the suggestion!

**Comment by albertoruiz** [comment]
I have added ldlPacked and ldlSolve.

**Comment by albertoruiz** [comment]
But we still need data types for the these {LU,LDL,etc.} packed structures, and also for symmetric/ hermitian matrices. I am working on this.
