### ISSUE TITLE
Move Numeric.LinearAlgebra.Static to a separate package

### ISSUE THREAD

**Issue by amigalemming** [albertoruiz/hmatrix#136]
`Numeric.LinearAlgebra.Static` contains advanced type tricks that are subject to changes in GHC. E.g. compilation with ghc-7.11.20150707 fails. How about moving the module to a separate package? Or is the module already subsumed by `hmatrix-static`?

**Comment by albertoruiz** [comment]
It is not subsumed, it is just an alternative interface with a different design. I hope that the compilation problems with ghc-7.11 could be fixed and there is no need of moving it.
