### ISSUE TITLE
Test failure on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by samvher** [albertoruiz/hmatrix#143]
I get an error running my tests after installing:

------ index
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
------ mult Double
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
------ mult Float
*** Failed! Falsifiable (after 11 tests and 1345 shrinks):      
Consistent ((3><6)
 [ 0.0, 0.0,  0.0,              0.0, 0.0,                0.0
 , 0.0, 0.0,  0.0,              0.0, 0.0,                0.0
 , 0.0, 0.0, -3.0, -9.1769028116329, 0.0, -2.029527817468682 ],(6><4)
 [ 0.0,                  0.0, 0.0,                   0.0
 , 0.0,                  0.0, 0.0,                   0.0
 , 0.0,                  0.0, 0.0, 1.3510389666962039e-6
 , 0.0,                  0.0, 0.0,  4.442635982213694e-6
 , 0.0,                  0.0, 0.0,                   0.0
 , 0.0, 8.105779377544555e-6, 0.0,    1.9725086205402484 ])
*** Exception: ExitFailure 1

I have some difficulty finding out how to test my LAPACK/BLAS installations (all I can find is how to test them after building by hand), but I have run the scipy test suite without unexpected failures (as far as I can tell this is linked against the default Accelerate BLAS and tests BLAS/LAPACK performance, I expect these are the same libraries hmatrix is linked against but I'm not sure).

Some advice on how to approach this would be more than welcome (I'm not very experienced with BLAS/LAPACK). The hmatrix library does look like something I will want to use regularly so I hope to fix this.

Thanks!

**Comment by albertoruiz** [comment]
This is a known problem in this version of the testing package: the tolerance of this particular test is too low and we may get failures even though the computation is numerically correct. Your system will most likely work perfectly.

New versions of the packages are almost ready in the master branch of this repository. They will be uploaded to Hackage in a few days, but you can try them now and check that all tests pass.

Thanks for the bug report!

**Comment by samvher** [comment]
Thanks for your fast response. Trying to build the new versions I ran into another issue which I'll open separately.
