### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by chadbrewbaker** [albertoruiz/hmatrix#145]
crb002s-MacBook-Pro:bin crb002$ ghci 
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> Numeric.LinearAlgebra.Tests.runTests 20
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package binary-0.7.1.0 ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package old-locale-1.0.0.6 ... linking ... done.
Loading package time-1.4.2 ... linking ... done.
Loading package HUnit-1.2.5.2 ... linking ... done.
Loading package random-1.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package primitive-0.5.4.0 ... linking ... done.
Loading package tf-random-0.5 ... linking ... done.
Loading package transformers-0.4.2.0 ... linking ... done.
Loading package QuickCheck-2.7.6 ... linking ... done.
Loading package split-0.2.2 ... linking ... done.
Loading package storable-complex-0.2.2 ... linking ... done.
Loading package vector-0.10.12.2 ... linking ... done.
Loading package hmatrix-0.16.1.5 ... linking ... done.
Loading package filepath-1.3.0.2 ... linking ... done.
Loading package unix-2.7.0.1 ... linking ... done.
Loading package directory-1.2.1.0 ... linking ... done.
Loading package process-1.2.0.0 ... linking ... done.
Loading package hmatrix-gsl-0.16.0.3 ... linking ... done.
Loading package hmatrix-tests-0.4.1.0 ... linking ... done.
------ index
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
------ mult Double
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
+++ OK, passed 100 tests.
------ mult Float
*** Failed! Falsifiable (after 16 tests and 1417 shrinks):      
Consistent ((10><3)
 [                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 ,                 0.0,               0.0,                0.0
 , -12.936396429620235, 0.818177091446717, -5.527482853442194
 ,                 0.0,               0.0,                0.0 ],(3><6)
 [ 0.0, 0.0, 0.0, 0.0, 0.0,  1.943796893214956e-9
 , 0.0, 0.0, 0.0, 0.0, 0.0, 2.5920836717467456e-2
 , 0.0, 0.0, 0.0, 0.0, 0.0,     5.793096464974948 ])
*** Exception: ExitFailure 1

**Comment by albertoruiz** [comment]
It is a known problem (wrong tolerance in a test, see https://github.com/albertoruiz/hmatrix/issues/144). 

You can try the new versions of the packages in the master branch.
