### ISSUE TITLE
How to scale a vector

### ISSUE THREAD

**Issue by sid-kap** [albertoruiz/hmatrix#153]
I tried to use the `Numeric.LinearAlgebra.scale` function to scale a statically-sized vector (`R 900`), but I kept getting type errors like:

```
    Couldn't match kind ‘*’ with ‘Nat’
    When matching types
      c :: * -> *
      R :: Nat -> *
    Expected type: c e
      Actual type: R 2
    Relevant bindings include it :: c e (bound at <interactive>:4:1)
    In the second argument of ‘LA.scale’, namely ‘(vec2 2 3)’
    In the expression: LA.scale 1 (vec2 2 3)
```
I guess I don't fully understand the types here, but I assume that R is an instance of the Linear typeclass, so this should work?

I also had similar difficulty with cmap, doing something like `LA.cmap log (vec2 4 5)`.

**Comment by albertoruiz** [comment]
The LA.* functions are usually not needed here (and only work with the dynamic arrays in the regular interface). Most operations in the static module are "automatic":

    λ> let v = vec2 1 2
    λ> v
    (vector [1.0,2.0] :: R 2)
    λ> 3 * v
    (vector [3.0,6.0] :: R 2)
    λ> konst (3::Double) * v
    (vector [3.0,6.0] :: R 2)
    λ> log v
    (vector [0.0,0.6931471805599453] :: R 2)

(I have updated the [tutorial](http://dis.um.es/~alberto/hmatrix/static.html))

**Comment by sid-kap** [comment]
Awesome, thank you so much!
