### ISSUE TITLE
cabal install hmatrix-gsl fails

### ISSUE THREAD

**Issue by acardona** [albertoruiz/hmatrix#160]
In ubuntu 14.04, with hmatrix 0.16.1.5 installed:

$ cabal install hmatrix-gsl
Resolving dependencies...
Configuring hmatrix-gsl-0.16.0.3...
cabal: The pkg-config package gsl is required but it could not be found.
Failed to install hmatrix-gsl-0.16.0.3
cabal: Error: some packages failed to install:
hmatrix-gsl-0.16.0.3 failed during the configure step. The exception was:
ExitFailure 1

Installing package gsl by itself fails too, of course:

$ cabal install gsl
cabal: There is no package named 'gsl'.
You may need to run 'cabal update' to get the latest list of available
packages.

I was led to expect from the package description at https://hackage.haskell.org/package/hmatrix-gsl that gsl was a package to be installed via cabal.

Would appreciate hints towards successfully installing hmatrix-gsl.

**Comment by albertoruiz** [comment]
You need the development package for gsl:

    $ sudo apt-get install libgsl0-dev

**Comment by acardona** [comment]
Thank you, that did it.
