### ISSUE TITLE
Update documentation: hmatrix-sparse dependency on MKL

### ISSUE THREAD

**Issue by sid-kap** [albertoruiz/hmatrix#165]
When I was building hmatrix on my machine, I, by habit, ran `stack install`, which tried to install every sub-package. Since I don't have Intel MKL on my computer, I ran into errors when this command tried to build `hmatrix-sparse`.

This confused me a lot. I assumed that hmatrix-sparse was needed by the other modules, so I spent a long time Googleing how to install MKL, until I finally realized that it is paid software. Finally, after reading #157, I realized that MKL and hmatrix-sparse are not required for the other modules.

Can we put a note somewhere (possibly in INSTALL.md) to instruct contributors that MKL and hmatrix-sparse is only for benchmarking and is not needed for most development? I think this will make it easier for people to get started in developing hmatrix.

**Comment by albertoruiz** [comment]
Sorry about this. I have removed hmatrix-sparse from the package list in the stack.yaml. I will soon update the Makefile and the installation instructions.
Thanks!
