### ISSUE TITLE
Binary IFDEFs

### ISSUE THREAD

**Issue by sid-kap** [albertoruiz/hmatrix#179]
I noticed there are a few `#IFDEF BINARY` checks in the code in `packages/base/src/internal/Vector.hs` and `packages/base/src/internal/Element.hs`. However, you also merged my PR #178 which didn't add these checks for the new `Binary` instances that I added for `R n` and `L m n`.

Should we go back and add these checks for `R n` and `L m n`? Or if not, are these checks not needed anymore? Should we remove all of the checks in that case?

**Comment by albertoruiz** [comment]
These checks are not needed anymore. We should remove them and also remove the "cpp-options: -DBINARY" line in hmatrix.cabal.

Thanks!
