### ISSUE TITLE
Vectorizing a function

### ISSUE THREAD

**Issue by m-renaud** [albertoruiz/hmatrix#189]
Looking through the API I couldn't find a function that allowed for the efficient application of a function to each element of a vector or matrix. It may not make sense for them to be instances of `Functor` since they can't hold elements of arbitrary type, but a function such as `vectorize` below is what I'm looking for.

`vectorize :: (t -> t) -> Vector t -> Vector t` 

Thoughts?

**Comment by mstksg** [comment]
You're looking for `cmap`, which is exported from `Numeric.LinearAlgebra` :)

~~~
cmap :: (Element b, Container c e) => (e -> b) -> c e -> c b
~~~

**Comment by m-renaud** [comment]
Thanks! I definitely missed that when reading through the docs, it appears to be exported from `Numeric.LinearAlgebra.Data`.
