### ISSUE TITLE
Corrupted memory when using hmatrix in a multi threaded settings

### ISSUE THREAD

**Issue by bitonic** [albertoruiz/hmatrix#198]
Me, @nh2 , @chpatrick, and @exFalso have been banging our heads on a bug that caused random segfaults in our program. We've managed to cut it down to a few lines of hmatrix here: https://github.com/bitonic/hmatrix-nasal-demons/blob/master/app/Main.hs . `async` is just used to make the main thread go down when one of them does, the same problem will pop up with simple `forkIO`s.

All the program does is repeated calls to `svd` + `<>` in 4 separate threads.

Run it with

```
$ stack build
$ stack exec -- hmatrix-nasal-demons 30
```

On a multicore machine. At some point (you might have to wait a few minutes) it'll fail with various errors pointing at corrupted memory, such as null pointer dereferences or "bad arguments" errors such as

```
 ** On entry to DLASCL parameter number  4 had an illegal value
```

We have analyzed the code in hmatrix, and while the calls (sometimes nested) to `unsafePerformIO`/`inlinePerformIO` certainly don't look good we could not pinpoint a place where their usages might be unsafe.

This might also be a GHC bug -- we're a bit stumped on how to debug it.

**Comment by bitonic** [comment]
I should add, `stack exec -- hmatrix-nasal-demons 30 +RTS -N1` never fails.

**Comment by mstksg** [comment]
fwiw, I've had this issue too, without luck in trying to fix it. thank you for opening an issue with a program with a reproducible demonstration :)

**Comment by exFalso** [comment]
We tracked it down with @bitonic to a subtle ForeignPtr escape from the `Data.Vector.unsafeWith` bracket, caused by the weird definition and usage of the `#` functions. Patch coming up
