### ISSUE TITLE
libopenblas: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by mohanr** [albertoruiz/hmatrix#225]
1,  Install https://sourceforge.net/projects/mingw-w64/files/ 
 2. git clone https://github.com/maxc01/hmatrix.git
 3. cd hmatrix\packages\base
 4. cabal install --flags=openblas --extra-lib-dirs=D:\OpenBLAS-v0.2.19-Win64-int32\lib --extra-include-dirs=D:\OpenBLAS-v0.2.19-Win64-int32\include
      

      D:\Git\rl\Reinforcement-Learning-An-Introduction-by-Richard-S.-Sutton-and-Andrew
     -G.-Barto>ghci
      GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
      Prelude> :load "simulator.hs"
      [1 of 1] Compiling Simulator        ( simulator.hs, interpreted )
      Ok, modules loaded: Simulator.
     *Simulator> :main
     <interactive>: libopenblas: %1 is not a valid Win32 application.
      can't load .so/.DLL for: libopenblas.dll (addDLL: could not load DLL)
      *Simulator>
      Leaving GHCi.

     D:\Git\rl\Reinforcement-Learning-An-Introduction-by-Richard-S.-Sutton-and-Andrew
    -G.-Barto>ghci
    GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
    Prelude> import Numeric.LinearAlgebra
    Prelude Numeric.LinearAlgebra> matrix 2 [1..6]
    <interactive>: libopenblas: The specified module could not be found.
    can't load .so/.DLL for: libopenblas.dll (addDLL: could not load DLL)
    Prelude Numeric.LinearAlgebra>

[Related Issue](https://github.com/albertoruiz/hmatrix/issues/184)

**Comment by mohanr** [comment]
Using stack I was able to fix this.

**Comment by raymoo** [comment]
What was the fix? I am getting the error even when using stack (stack repl)
