### ISSUE TITLE
The pkg-config package 'gsl' is required but it could not be found.

### ISSUE THREAD

**Issue by mohanr** [albertoruiz/hmatrix#226]
Process exited with code: ExitFailure 1
                  Logs have been written to: D:\CS294\hmatrix-test\.stack-work\logs\hmatrix-gs
                  l-0.18.0.1.log

                  Configuring hmatrix-gsl-0.18.0.1...
                  setup-Simple-Cabal-1.24.2.0-ghc-8.0.2.exe: The pkg-config package 'gsl' is
                  required but it could not be found.

My command is this.

                  stack --extra-lib-dirs=D:/CS294/gsl-1.8-bin/bin build hmatrix-tests

I am using [gsl](http://gnuwin32.sourceforge.net/packages/gsl.htm) and point lib dir to its bin.
Everything else is installed by Stack.

But even if I use gsl-lapack-windows like this I see the same error.

              flags:
              hmatrix:
              openblas: true
              extra-package-dbs: []
              packages:
              - '.'
             extra-deps:
            - hTensor-0.9.1
           - hmatrix-0.18.0.0
             resolver: lts-8.5
             extra-lib-dirs:
            - D:\CS294\OpenBLAS-v0.2.19-Win64-int32\OpenBLAS-v0.2.19-Win64-int32\bin
           - D:\CS294\gsl-lapack-windows
            extra-include-dirs:
            - D:\CS294\OpenBLAS-v0.2.19-Win64-int32\OpenBLAS-v0.2.19-Win64-int32\include
          - D:\CS294\gsl-lapack-windows\gsl

**Comment by stla** [comment]
I think you need to install `mingw-w64-gsl` as explained here: https://github.com/Alexpux/MINGW-packages

**Comment by idontgetoutmuch** [comment]
@mohanr Has your problem been solved? I am triaging issues and I would like to close this if it is no longer an issue for you.

**Comment by idontgetoutmuch** [comment]
@mohanr please reopen if this is still a problem.

**Comment by kewp** [comment]
In fact, to work I had to run `stack exec -- pacman -S mingw-w64-x86_64-gsl` though now it says it can't find `gsl-0` (maybe editting hmatrix-gsl.cabal and changing the `gsl-0` reference to `gsl` will work...)
