### ISSUE TITLE
hmatrix-glpk: feasible solution / objective function with zero variables

### ISSUE THREAD

**Issue by jwaldmann** [albertoruiz/hmatrix#239]
I just want a some feasible solution for an LP. 

I thought I'd just get this with `goal = Maximize []` 
but it's rejected by hmatrix-glpk. Why? Could the underlying GLPK solver do this? Or would it have a different method for that? Which could then be expose to Haskell land? 

Actually my expectation was
`data Optimization = Maximize [Double]  | Minimize [Double] | Feasible`.

**Comment by albertoruiz** [comment]
Sorry for the late reply.

You can use a dummy cost (e.g. [1,1...]) to avoid the error.

I agree that looking only for a feasible solution would be a good and faster option. I don't remember at the moment if you can do this easily with glpk.

**Comment by idontgetoutmuch** [comment]
@jwaldmann does that work for you? I am going to close the issue but feel free to re-open.

**Comment by jwaldmann** [comment]
> I agree that looking only for a feasible solution would be a good and faster option. I don't remember at the moment if you can do this easily with glpk.

https://en.wikibooks.org/wiki/GLPK/Modeling_tips#All_feasible_solutions suggests 
* zero objective function (you said `[1, .. 1]` but it should be `[0, .. 0]`?)
* omit objective function

I will look into this.
