### ISSUE TITLE
Incorrect dotproduct in `Numeric.LinearAlgebra.Static`

### ISSUE THREAD

**Issue by SamDM** [albertoruiz/hmatrix#241]
Using `hmatrix 0.18.0.0` from stack `lts-9.6`, I get the following weird behaviour:
```{haskell}
λ: a = 1 :: R 3
λ: disp 2 a
R 3
1  1  1
λ: b = vec3 1 1 1
λ: disp 3 b
R 3
1  1  1
λ: a <.> 1 -- Wrong result?
1.0
λ: b <.> 1
3.0
```
Am I the only one seeing this bug?

Here are some details about my system:
```
$ uname -a
Linux sam-pc 4.9.51-1-MANJARO #1 SMP PREEMPT Wed Sep 20 10:37:40 UTC 2017 x86_64 GNU/Linux
$ pacman -Qs blas
local/blas 3.7.1-2
    Basic Linear Algebra Subprograms
$ pacman -Qs lapack
local/lapack 3.7.1-2
    Linear Algebra PACKage
$ pacman -Qs stack
local/haskell-stack-git 1.5.1.r363.g7b07c469-1
    The Haskell Tool Stack
```

**Comment by albertoruiz** [comment]
The definition should be

    dotR :: KnownNat n => R n -> R n -> ℝ
    dotR (extract -> u) (extract -> v) = LA.dot u v

and the same thing for dotC.

**Comment by albertoruiz** [comment]
I have pushed a fix. Please check that it is now ok.

**Comment by SamDM** [comment]
Ok, now I get the following problem:

```
λ: let a = 3 :: R 3
λ: a <.> 1
/home/samdm/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-7.10.2/lib/ghc-7.10.2/bin/ghc: symbol lookup error: /tmp/ghc13689_0/libghc_1.so: undefined symbol: dgemm_
```

Any advice?

**Comment by albertoruiz** [comment]
It looks like ghc cannot find the external lapack library. (dgemm_ is the basic matrix multiplication function.) Do you get any error with other hmatrix functions?

**Comment by SamDM** [comment]
Strange, the following works:

```
λ: :l Numeric.LinearAlgebra
λ: vector [1,2,3] * vector [3,0,-2]
fromList [3.0,0.0,-6.0]
λ: matrix 3 [1..9] * ident 3
(3><3)
 [ 1.0, 0.0, 0.0
 , 0.0, 5.0, 0.0
 , 0.0, 0.0, 9.0 ]
```

**Comment by SamDM** [comment]
Ok, this fails as well:
```
vector [1,2,3,4] <.> vector [-2,0,1,1]
```
Same error

**Comment by SamDM** [comment]
Ok, switching to a newer version of ghc did the trick. Essentially I set the resolver to `lts-9.6` in the `stack.yaml` of the `base` package of hmatrix.

Anyhow, the original bug is fixed, but I wonder if this is the intended behavior:
```
λ: :l Numeric.LinearAlgebra.Static Internal.Static
λ: a = 1 :: R 3
λ: b = vec3 1 1 1 :: R 3
λ: ud1 a
[1.0]
λ: ud1 b
[1.0,1.0,1.0]
```

**Comment by albertoruiz** [comment]
ud1 is an internal function, not intended to be used by the end user.
In fact you cannot import Internal.Static from a normal installation, it is a hidden module.

Use extract to get a normalized dynamic vector.

**Comment by SamDM** [comment]
Ok, then I believe this issue is solved. Thank you for the quick fix 👍
