### ISSUE TITLE
Please release new versions that include 'disable-default-paths' flag

### ISSUE THREAD

**Issue by peti** [albertoruiz/hmatrix#243]
Basically, none of those hmatrix builds work with Nix because the Cabal files contain hard-coded impure search paths. I see that a fix was committed to `master` some 8 months ago. It would be really nice to have that `disable-default-paths` flag available at last.

**Comment by albertoruiz** [comment]
I will release a new version asap.
Thanks for your message.

**Comment by peti** [comment]
Ping?

**Comment by idontgetoutmuch** [comment]
@albertoruiz Might I suggest that you make me a collaborator on GitHub with the ability to merge PRs and also give me permission to upload new versions to Hackage? That way I can deal with minor changes like the one @peti (and I) would like.

**Comment by albertoruiz** [comment]
Yes, this is a good idea. I would be very grateful If you can help with this.

**Comment by albertoruiz** [comment]
I have just uploaded hmatrix-0.18.2 to hackage.

**Comment by albertoruiz** [comment]
@idontgetoutmuch I made you a collaborator on github. How can I give you permission to upload to Hackage?

**Comment by idontgetoutmuch** [comment]
Go here https://hackage.haskell.org/user/AlbertoRuiz and then select each package. You should see something like https://hackage.haskell.org/package/hmatrix/maintainers. Click on edit and add me as a user. I am DominicSteinitz on Hackage.

**Comment by albertoruiz** [comment]
Done!

Thanks for your help!
