### ISSUE TITLE
cabal file is not right

### ISSUE THREAD

**Issue by idontgetoutmuch** [albertoruiz/hmatrix#246]
I think there are two issues:

1. The paths for osx are hard-coded. I do *not* have e.g. `/opt/local/lib/openblas/lib`; I don't even have `/opt`. I am on OSX.

2. If I use `openblas` via nix, it looks like it is taking one of the branches where "if flag(openblas)" is expect but the openblas flag isn't set and I get

```
Setup: hmatrix.cabal:120: 'then' branch of 'if' is empty
```

**Comment by idontgetoutmuch** [comment]
I don't know how to fix this yet.

**Comment by peti** [comment]
This issue would be solved, basically, if we could get a Hackage release of the current state from git: https://github.com/albertoruiz/hmatrix/issues/243.

**Comment by idontgetoutmuch** [comment]
I think this is now solved. I still think the cabal file is not quite right but the consequences are benign. I may create a ticket in the future if I can think of a better cabal.

**Comment by alexanderkjeldaas** [comment]
Is this solved?     Seems like hmatrix still has the wrong hard-coded path.

```
openblas is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BLAS and LAPACK in the Accelerate framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/usr/local/opt/openblas/lib"
  export CPPFLAGS="-I/usr/local/opt/openblas/include"

For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"
```

https://github.com/haskell-numerics/hmatrix/blob/master/packages/base/hmatrix.cabal#L105
