### ISSUE TITLE
Using hmatrix with Atom / iHaskell

### ISSUE THREAD

**Issue by OscarSouth** [albertoruiz/hmatrix#247]
I installed according to instructions provided on this GitHub.

It works fine in GHCi (here's a line I took from a tutorial)

```
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> import Numeric.LinearAlgebra
Prelude Numeric.LinearAlgebra> vector [1,2,3] * vector [3,0,-2]
[3.0,0.0,-6.0]
Prelude Numeric.LinearAlgebra> 
```

In Atom (Hydrogen - iHaskell kernel) it fails horribly, however.

The library will import fine, but once I try and run that same line of code, the iHaskell kernal crashes and the following error is returned.

![image](https://user-images.githubusercontent.com/32574713/35237316-3dcf08e6-ffa2-11e7-9c80-26592112b1eb.png)

![image](https://user-images.githubusercontent.com/32574713/35237286-265d50d2-ffa2-11e7-9334-24f080585d59.png)

Is there any way that I can run hmatrix inline, using Atom/iHaskell/Hydrogen?

Thanks,
Oscar

**Comment by idontgetoutmuch** [comment]
I don't think this is an hmatrix issue but please re-open if you think I have misunderstood.
