### ISSUE TITLE
Can't install hmatrix on Windows

### ISSUE THREAD

**Issue by darkus** [albertoruiz/hmatrix#25]
Greetings.

Did what is written at https://github.com/AlbertoRuiz/hmatrix/blob/master/INSTALL.md:

1. Updated cabal list
2. Downloaded and installed GSL into C:/ProgramData/GSL
3. cabal install hmatrix-0.13.1.0 --extra-lib-dir=C:/ProgramData/GSL --extra-include-dir=C:/ProgramData/GSL

First issue: the hmatrix-tests package tries to install hmatrix-0.14.1.0 and fails.

Second issue:

Prelude> :m +Data.Packed.Matrix

Prelude Data.Packed.Matrix> (2 >< 3) [1..6]

Loading package array-0.4.0.0 ... linking ... done.
Loading package deepseq-1.3.0.0 ... linking ... done.
Loading package containers-0.4.2.1 ... linking ... done.
Loading package bytestring-0.9.2.1 ... linking ... done.
Loading package binary-0.5.1.0 ... linking ... done.
Loading package Win32-2.2.2.0 ... linking ... done.
Loading package filepath-1.3.0.0 ... linking ... done.
Loading package old-locale-1.0.0.4 ... linking ... done.
Loading package old-time-1.1.0.0 ... linking ... done.
Loading package directory-1.1.0.2 ... linking ... done.
Loading package process-1.1.0.1 ... linking ... done.
Loading package storable-complex-0.2.1 ... linking ... done.
Loading package primitive-0.4.1 ... linking ... done.
Loading package vector-0.9.1 ... linking ... done.
Loading package hmatrix-0.13.1.0 ... <interactive>: gsl-0: ═х эрщфхэ єърчрээ√щ ьюфєы№.
can't load .so/.DLL for: gsl-0.dll (addDLL: could not load DLL)

(The weird string "═х эрщфхэ єърчрээ√щ ьюфєы№" means "The specified module not found").

What I do wrong?

**Comment by stla** [comment]
`gsl-0` is not `gsl`. I'm also looking for it...

**Comment by stla** [comment]
This is `libgslcblas-0.dll` actually. I have just renamed to `libgsl-0.dll` and `hmatrix-gsl` was installed. But not tested yet.

**Comment by kewp** [comment]
I'm having the same issue. What is `gsl-0` ?

**Comment by idontgetoutmuch** [comment]
Can you post what you did exactly? Are you using stack? Cabal?

**Comment by kewp** [comment]
I've tried everything but the furthest I got was with stack.

I need to check but it was something like `stack install hmatrix-gsl --flags hmatrix:openblas`

I've also done it with Lapack. Those parts went through fine (not through using the extra-libs add-on but rather with `stack exec -- pacman -S mingw-m64-x86_64-lapack`, etc) but there are no mingw packages for libgsl0-dev....

And strangely it looks like the .cabal file for hmatrix-gsl says only the windows version needs gsl-0 (and not just gsl) ?
