### ISSUE TITLE
Build failure on Windows 8.1 64-bit

### ISSUE THREAD

**Issue by is7s** [albertoruiz/hmatrix#69]
When building hmatrix latest version I get:

Failed to install hmatrix-0.15.2.1 
Last 10 lines of the build log ( C:\Users\is7s\AppData\Roaming\cabal\logs\hm
atrix-0.15.2.1.log ):
setup.exe: Package hmatrix-0.15.2.1 can't be built on this system.
cabal.exe: Error: some packages failed to install:
hmatrix-0.15.2.1 failed during the building phase. The exception was:
ExitFailure 1

And when building hmatrix-0.13.1.0 I get:

Failed to install hmatrix-0.13.1.0
Last 10 lines of the build log ( C:\Users\is7s\AppData\Roaming\cabal\logs\hm
atrix-0.13.1.0.log ):
Configuring hmatrix-0.13.1.0...
"#include <gsl/gsl_sf_gamma.h>
"#include <gsl/gsl_sf_exp.h>
Checking foreign libraries... OK
setup.exe: Missing dependencies on foreign libraries:
* Missing C libraries: gsl-0, blas, lapack
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
cabal.exe: Error: some packages failed to install:
hmatrix-0.13.1.0 failed during the configure step. The exception was:
ExitFailure 1

I've followed the instructions in the INSTALL file, added the relevant directories to ${PATH} and ${GSL}.

What's wrong?

**Comment by dreixel** [comment]
I do have this problem; the libraries supplied in the zip file are 32 bit, but my GHC is 64 bit. Could you also supply the 64bit libraries?

**Comment by albertoruiz** [comment]
Sorry, I don't have the 64bit version, but I have found some interesting links:

http://icl.cs.utk.edu/lapack-for-windows/lapack/

https://groups.google.com/forum/#!topic/openblas-users/OlIxlzsOHSs

**Comment by stla** [comment]
Does anyone know where we can found `gsl-0` ?

**Comment by stla** [comment]
Nice. I have renamed `libgslcblas-0.dll` to `libgsl-0.dll` and `hmatrix-gsl` was installed.
